#!/bin/sh

dotnet publish -r linux-arm -c Publish --self-contained -o ./Publish/elmx_linux-arm
dotnet publish -r linux-arm64 -c Publish --self-contained -o ./Publish/elmx_linux-arm64
dotnet publish -r linux-musl-arm64 -c Publish --self-contained -o ./Publish/elmx_linux-musl-arm64
dotnet publish -r linux-musl-x64 -c Publish --self-contained -o ./Publish/elmx_linux-musl-x64
dotnet publish -r linux-x64 -c Publish --self-contained -o ./Publish/elmx_linux-x64
dotnet publish -r osx-arm64 -c Publish --self-contained -o ./Publish/elmx_osx-arm64
dotnet publish -r osx-x64 -c Publish --self-contained -o ./Publish/elmx_osx-x64