#!/bin/sh

dotnet publish -r linux-arm -c Publish --self-contained
dotnet publish -r linux-arm64 -c Publish --self-contained
dotnet publish -r linux-musl-arm64 -c Publish --self-contained
dotnet publish -r linux-musl-x64 -c Publish --self-contained
dotnet publish -r linux-x64 -c Publish --self-contained
dotnet publish -r osx-arm64 -c Publish --self-contained
dotnet publish -r osx-x64 -c Publish --self-contained